### ISSUE TITLE
song_warchdog.exe

### ISSUE THREAD

**Issue by lunasea0083** [UiharuKazari2008/SOS-Keychip#1]
Is this document savior_of_song_warchdog.exe missing?

**Comment by UiharuKazari2008** [comment]
The releases were not updated, This has been corrected. Sorry about that
https://github.com/UiharuKazari2008/SOS-Keychip/releases/tag/release

**Comment by UiharuKazari2008** [comment]
Closing this because the watchdog is now built in (--watchdog) or just use --launchApp to have it handled the game and watching for removal of hardware
